glad_laser_filter:
  ros__parameters:
    input_scan_topic: /scan_unfiltered
    output_scan_topic: /scan
    target_beams: 544

    filter1:
      name: angle
      type: angular_bounds
      lower_angle: 1.5708
      upper_angle: -1.5708

    filter2:
      name: range
      type: range_filter
      min_range: 0.20
      max_range: 12.0
